### ISSUE TITLE
Android "RNSVGSvgView" was not found in the UIManager.

### ISSUE THREAD

**Issue by songhanlin** [cantoo-scribe/rn-svg#1]
ERROR  Invariant Violation: requireNativeComponent: "RNSVGSvgView" was not found in the UIManager.

This error is located at:
    in RNSVGSvgView (created by Svg)
    in Svg (created by SvgAst)
    in SvgAst (created by SvgXml)
    in SvgXml (created by TabMainScreen)
    in RCTView (created by View)
    in View (created by NativeLinearGradient)
    in NativeLinearGradient (created by LinearGradient)
    in LinearGradient (created by TabMainScreen)
    in RCTView (created by View)
    in View (created by View)
    in View (created by TabMainScreen)
    in TabMainScreen
    in Unknown (created by Route(home))
    in Suspense (created by Route(home))
    in Route (created by Route(home))
    in Route(home) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by BottomTabView)
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous) (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by BottomTabView)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator
    in Unknown (created by TabLayout)
    in TabLayout
    in Unknown (created by Route((tabs)))
    in Suspense (created by Route((tabs)))
    in Route (created by Route((tabs)))
    in Route((tabs)) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous) (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator
    in Unknown (created by StackRoute)
    in StackRoute (created by RootLayoutNav)
    in SessionProvider (created by RootLayoutNav)
    in RCTView (created by View)
    in View (created by Portal.Host)
    in Portal.Host (created by Provider)
    in ThemeProvider (created by Provider)
    in LocaleProvider (created by Provider)
    in Provider (created by RootLayoutNav)
    in RootLayoutNav (created by RootLayout)
    in RootLayout
    in Try
    in Unknown
    in Unknown (created by Route())
    in Suspense (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes

<SvgXml />
ReactNative:0.74.2
expo: ~51.0.17
@cantoo/rn-svg: 13.0.4(ps: ios/web is ok)
react-native-svg: 15.2.0(ps: ios/android is ok)

---
I also use "react-native-qrcode-svg": "^6.3.1", bug react-native-qrcode-svg need react-native-svg, then i fork react-native-qrcode-svg and change  react-native-svg to @cantoo/rn-svg, and got this error.

please help me~~😭

**Comment by songhanlin** [comment]
In the same project , cannot use @cantoo/rn-svg and react-native-svg at the same time. (run on ios, not yet tried on android, web is ok)

**Comment by songhanlin** [comment]
I use your changes and solve my problem, thank you!

**Comment by 0000005** [comment]
@songhanlin  How to solve this problem? can you share more information about this.
